using System;
using System.Collections.Generic;
using System.Data.SqlServerCe;
using System.IO;
using System.Linq;
using System.Text;

using SdfConverter.Dialects;
using SdfConverter.Models;
using SdfConverter.Sdf;

namespace SdfConverter.Writing;

/// <summary>
/// Generates SQL files for a chosen target dialect. Emits an idempotent CREATE TABLE
/// followed by batched INSERT statements, with all rendering delegated to the dialect.
/// </summary>
public sealed class SqlWriter
{
    /// <summary>Default records per INSERT batch.</summary>
    public const int DefaultBatchSize = 1000;

    private readonly ISqlDialect _dialect;

    /// <summary>Creates a writer that renders SQL through the given dialect.</summary>
    public SqlWriter(ISqlDialect dialect)
    {
        _dialect = dialect ?? throw new ArgumentNullException(nameof(dialect));
    }

    /// <summary>
    /// Exports the given tables into one combined .sql file: opens the file once,
    /// writes a header, then streams each table in turn.
    /// </summary>
    public StreamingExportResult ExportDatabase(
        SqlCeConnection connection,
        IReadOnlyList<TableSchema> schemas,
        string outputPath,
        SourceMetadata metadata,
        Func<TableSchema, IProgress<int>?>? progressFactory = null,
        Action<TableSchema>? onTableStart = null)
    {
        if (string.IsNullOrWhiteSpace(outputPath))
        {
            throw new ArgumentException("Output path cannot be null or empty.", nameof(outputPath));
        }

        if (schemas == null) throw new ArgumentNullException(nameof(schemas));
        if (metadata == null) throw new ArgumentNullException(nameof(metadata));

        var totalRecords = 0;
        var totalSkipped = 0;
        var totalBatches = 0;
        var warnings = new List<string>();

        try
        {
            using (var output = new StreamWriter(outputPath, false, Encoding.UTF8, bufferSize: 65536))
            {
                WriteHeader(output, metadata);

                foreach (var schema in schemas)
                {
                    onTableStart?.Invoke(schema);

                    output.WriteLine($"-- Table: {schema.TableName} ({schema.RowCount:N0} rows)");

                    WriteCreateTable(output, schema);

                    var progress = progressFactory?.Invoke(schema);
                    var result = SdfReader.StreamTableInto(this, output, connection, schema, progress);

                    totalRecords += result.RecordsWritten;
                    totalSkipped += result.SkippedCount;
                    totalBatches += result.BatchCount;
                    foreach (var w in result.Warnings)
                    {
                        warnings.Add($"{schema.TableName}: {w}");
                    }
                }

                output.Flush();
            }
        }
        catch (IOException ex)
        {
            throw new IOException($"Failed to write SQL file to '{outputPath}': {ex.Message}", ex);
        }

        var fileInfo = new FileInfo(outputPath);
        var fileSizeBytes = fileInfo.Exists ? fileInfo.Length : 0;

        return new StreamingExportResult(totalRecords, totalSkipped, totalBatches, fileSizeBytes, warnings);
    }

    private void WriteHeader(StreamWriter writer, SourceMetadata metadata)
    {
        writer.WriteLine("-- Generated by SdfConverter");
        writer.WriteLine($"-- Source: {metadata.SdfFileName}");
        writer.WriteLine($"-- Table: {metadata.TableName}");
        writer.WriteLine($"-- Records: {metadata.RecordCount:N0}");
        writer.WriteLine($"-- Generated: {DateTimeOffset.Now:yyyy-MM-ddTHH:mm:sszzz}");
        writer.WriteLine();
    }

    private void WriteCreateTable(StreamWriter writer, TableSchema schema)
    {
        writer.WriteLine(_dialect.CreateTableHeader(schema.TableName));

        for (var i = 0; i < schema.Columns.Count; i++)
        {
            var column = schema.Columns[i];
            var nullability = column.IsNullable ? "" : " NOT NULL";
            var isLast = i == schema.Columns.Count - 1;
            var separator = isLast ? "" : ",";
            writer.WriteLine($"  {_dialect.QuoteIdentifier(column.ColumnName)} {_dialect.MapColumnType(column)}{nullability}{separator}");
        }

        writer.WriteLine(");");
        writer.WriteLine();
    }

    /// <summary>Writes one multi-row INSERT for a batch of records.</summary>
    public void WriteDynamicBatch(StreamWriter writer, IReadOnlyList<DynamicRecord> records, TableSchema schema)
    {
        var columnNames = string.Join(", ", schema.Columns.Select(c => _dialect.QuoteIdentifier(c.ColumnName)));
        writer.WriteLine($"INSERT INTO {_dialect.QualifyTable(schema.TableName)} ({columnNames})");
        writer.WriteLine("VALUES");

        for (var i = 0; i < records.Count; i++)
        {
            var record = records[i];
            var values = new List<string>();

            foreach (var column in schema.Columns)
            {
                if (record.Values.TryGetValue(column.ColumnName, out var value))
                {
                    values.Add(_dialect.FormatValue(value, column.DataType));
                }
                else
                {
                    values.Add("NULL");
                }
            }

            var isLast = i == records.Count - 1;
            var separator = isLast ? "" : ",";
            writer.WriteLine($"  ({string.Join(", ", values)}){separator}");
        }

        writer.WriteLine(";");
        writer.WriteLine();
    }
}
